#!/usr/bin/env ruby

usage =<<EOF

      #{$0} names distr

      ------------------------------------------------------
      * names    :: simulated_reads_transcripts_test2.txt
      * distr    :: simulated_reads_gene_distribution_test2.txt
      ------------------------------------------------------

      Creates spreadsheet with the actual expression levels
      of the genes in names.

                                                   by khayer

EOF

if ARGV.length != 2
  puts usage
  exit
end

names = ARGV[0]
distr = ARGV[1]

STDOUT.puts "GenName\tExpressionLevel"

genes_names = Hash.new
File.open(names).each do |line|
  next unless line =~ /^genes/
  line.chomp!
  genes_info = line.split(" = ")
  genes_names[genes_info[0]] = genes_info[1]
end

last_distribution = 0

File.open(distr).each do |line|
  line.chomp!
  distr_info = line.split(" = ")
  if genes_names[distr_info[0].sub(/_distribution/,"s")]
    gene_name = genes_names[distr_info[0].sub(/_distribution/,"s")]
  else
    raise "Could not find name for #{line}!"
  end
  current = distr_info[1].to_f - last_distribution
  last_distribution = distr_info[1].to_f
  STDOUT.puts "#{gene_name}\t#{current}"
end